### ISSUE TITLE
Add navbar and CSS styling to Delphi blog

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/delphi-blog#1]
@sgratzl , can you help us make this blog match the COVIDcast website as much as possible, before its release on Tuesday?

This includes:

- [ ] Adding the navbar
- [ ] "some executive direction on typography so font faces, sizes, header conventions, etc match throughout" - @zackchase 

I presume we could borrow most of this from https://www.cmu.edu/common/standard-v6/css/main.min.css

@capnrefsmmat says: "We have the ability to use any [Hugo theme](https://themes.gohugo.io/tags/blog/) or build our own [from a minimal template](https://github.com/yihui/hugo-xmin), as well as modifying the current theme however we want; I just picked this one because it was minimal, clean, and easy to tweak."

**Comment by capnrefsmmat** [comment]
Some pointers:

* This site is based on Hugo, specifically the [noteworthy theme](https://github.com/kimcc/hugo-theme-noteworthy). We can change themes if desired.
* The theme is in `themes/`, plus some modifications I made in `layouts/`.
* Instructions for building the site (to preview it) are in the README. If you don't have R but can install Hugo, you should just be able to use hugo to build it, since you don't need to rebuild the posts themselves.

I think we just need a minimal starter for Tuesday and then can work our way upward to a fully unified theme later.

**Comment by sgratzl** [comment]
ok will take a look on it on Monday morning.
