### ISSUE TITLE
deployment build question

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-blog#2]
In the README it states several times that one shouldn't commit to the public directory. 

why not have the following workflow?

use a github action that builds the main branch and commits the built website into the gh-pages branch in the root directory.

an alternative would be to use netlify/vercel or another service doing a similar thing without commit built files to the repo

**Comment by capnrefsmmat** [comment]
Since posts are in R Markdown, they can contain arbitrary R code to build graphics and results. If we want to automate the workflow (which would be great), we'd need a system that has a bunch of common R packages installed, and the ability to install new ones when someone decides to use a new package in their post.

The current approach exists basically so I can run the build step, make sure the R worked, and then push. Also so that people don't push draft posts into `public/` accidentally.
