### ISSUE TITLE
Improve automation for generating post HTML

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-blog#39]
#3 created a GitHub Action that uses blogdown to build the blog. We could use this to build the HTML needed for deployment, but

* github-deploy-repo only knows how to deploy from `main`, so we can't deploy to a separate `gh-pages` branch
* building individual blog posts can take a long time, so we might eat up our free CI allocation
* every time someone uses a new R package, we need to add it to `R/prepare.R`, or CI will fail
* there's no preview for PRs

Instead I build the HTML and commit it to `public/` manually, which is laborious and error-prone. (For example, if you build the HTML on a branch and then merge it, you may lose changes that occurred on main in the mean time, or generate weird HTML when resolving the merge.)

Is there a CI solution that would do a better job with these?

cc @sgratzl, since you made the initial GitHub Actions scheme

**Comment by sgratzl** [comment]
so far I haven't found a good solution. I failed to use [netlify](https://www.netlify.com/) nor [vercel](https://vercel.com/) to build hugo + blogdown since I wasn't able to install R in their build environment. 

>     * every time someone uses a new R package, we need to add it to `R/prepare.R`, or CI will fail
which is fine for me, since you should document your dependencies anyhow. Otherwise others won't be able to build the blog.

One option might be to check-in the compiled HTML files that are generated by blogdown in the `/content` directory along with its figures. This is also recommended by the blogdown owners itself. Howerver, you still have the merge problem you mentioned. In addition, when someone makes changes directly through the Github UI without re-generating the file it will be out of sync. We could have a Github action that is checking in a compiled version but that might be doomed for creating merge-conflicts. 

Another aspect besides the long generation time is that dependencies (and data) change over time. I'm not sure whether generating a blog post in a month will produce the same result as right now.

**Comment by sgratzl** [comment]
as part of the website redesign we likely merge the main website with the blog: https://github.com/cmu-delphi/www-main/pull/23 is the corresponding PR which also preserves the history. It also includes (after a long playing) a proper Github action which can build the blog posts (including caching). In addition, the compiled HTML files and assets are included in the repo which allows a simple preview.

**Comment by sgratzl** [comment]
closing in part of www-main version
